name: Code Build Workflow

on:
  workflow_run:
    workflows: 
      - Sonar Code Review Workflow
    types:
      - completed
        
jobs:
  build:
    name: Build
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Docker build and push
        run: |
          docker build -t Assignment-26_06_2024 .
          docker tag Assignment-26_06_2024 howaboutwepullsomeimages/Assignment-26_06_2024:latest
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
          docker push howaboutwepullsomeimages/Assignment-26_06_2024:latest
        env:
          DOCKER_CLI_ACI: 1
