name: Trivy Image Scan Workflow

on:
    workflow_run:
      workflows: 
        - Code Build Workflow
      types:
        - completed
  
jobs:
    build:
      name: Docker Image Scan
      runs-on: self-hosted
      steps:
        - name: Checkout Repository
          uses: actions/checkout@v2

        - name: Pull the Docker image
          run: docker pull howaboutwepullsomeimages/assignment-26_06_2024:latest

  
        - name: Trivy image scan
          run: trivy image howaboutwepullsomeimages/assignment-26_06_2024:latest 
